#!/usr/bin/env python3
"""Convert legacy generated Caddy route files with the canonical Nginx renderer."""

import argparse
import os
import re
from pathlib import Path
from urllib.parse import urlsplit

from nginx_renderer import (
    DEFAULT_CA_BUNDLE,
    RendererError,
    RouteSpec,
    normalize_origin,
    normalize_public_host,
    render_route,
    resolve_public_upstream_ips,
)


MARKER = re.compile(r"^# generated by uniproxy(?: panel)? for (https?://[^\r\n]+)$", re.MULTILINE)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--suffix", required=True)
    parser.add_argument("--cert", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--public-port", required=True, type=int)
    parser.add_argument("--internal-port", default=443, type=int)
    parser.add_argument("--ca-bundle", default=DEFAULT_CA_BUNDLE)
    parser.add_argument(
        "--allow-insecure-http",
        action="store_true",
        help="explicit legacy-only override; HTTPS remains the default",
    )
    args = parser.parse_args()
    try:
        suffix = normalize_public_host(args.suffix)
    except RendererError as exc:
        raise SystemExit("invalid domain suffix") from exc
    if not 1 <= args.public_port <= 65535:
        raise SystemExit("invalid public port")
    if not 1 <= args.internal_port <= 65535 or args.internal_port == 80:
        raise SystemExit("invalid internal HTTPS port")
    args.output.mkdir(parents=True, exist_ok=True)
    converted = 0
    for source in sorted(args.source.glob("*.caddy")):
        match = MARKER.search(source.read_text(encoding="utf-8"))
        if not match:
            continue
        try:
            public_host = normalize_public_host(source.stem)
        except RendererError as exc:
            raise SystemExit(f"refusing unexpected generated host: {source.stem}") from exc
        if not public_host.endswith("." + suffix):
            raise SystemExit(f"refusing unexpected generated host: {public_host}")
        try:
            origin = normalize_origin(
                match.group(1), allow_insecure_http=args.allow_insecure_http,
            )
            parsed = urlsplit(origin)
            default_port = 443 if parsed.scheme == "https" else 80
            upstream_ips = resolve_public_upstream_ips(parsed.hostname or "", parsed.port or default_port)
            content = render_route(RouteSpec(
                origin=origin,
                public_host=public_host,
                upstream_ips=upstream_ips,
                tls_cert_file=args.cert,
                tls_key_file=args.key,
                public_https_port=args.public_port,
                internal_https_port=args.internal_port,
                ca_bundle=args.ca_bundle,
                allow_insecure_http=args.allow_insecure_http,
            ))
        except RendererError as exc:
            raise SystemExit(f"refusing unsafe route from {source}: {exc}") from exc
        target = args.output / f"{public_host}.conf"
        temporary = target.with_suffix(target.suffix + ".new")
        temporary.write_text(content, encoding="utf-8")
        os.replace(temporary, target)
        converted += 1
    print(f"converted={converted}")


if __name__ == "__main__":
    main()
