#!/usr/bin/env python3
"""Convert generated uniproxy Caddy route files to Nginx server blocks."""

import argparse
import os
import re
from pathlib import Path
from urllib.parse import urlsplit


SAFE_HOST = re.compile(r"^[a-z0-9][a-z0-9.-]{0,252}$")
MARKER = re.compile(r"^# generated by uniproxy(?: panel)? for (https?://[^\r\n]+)$", re.MULTILINE)
REQUEST_HEADERS_TO_DROP = (
    "X-Forwarded-For", "X-Forwarded-Host", "X-Forwarded-Port", "X-Forwarded-Proto",
    "X-Real-IP", "Forwarded", "Via", "CF-Connecting-IP", "CF-IPCountry", "CF-Ray",
    "CF-Visitor", "CDN-Loop", "True-Client-IP", "Client-IP", "Fastly-Client-IP",
    "Proxy-Client-IP", "WL-Proxy-Client-IP", "X-Client-IP", "X-Cluster-Client-IP",
    "X-Originating-IP", "X-Remote-Addr", "X-Remote-IP",
)
RESPONSE_HEADERS_TO_DROP = (
    "Alt-Svc", "CF-Cache-Status", "CF-Ray", "NEL", "Report-To", "Server",
    "Speculation-Rules", "Via", "X-Powered-By", "X-AspNet-Version", "X-AspNetMvc-Version",
    "X-Backend-Server", "X-Cache", "X-Cache-Hits", "X-Runtime", "X-Served-By", "X-Timer",
)


def nginx_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def normalize_origin(value: str) -> str:
    parsed = urlsplit(value.strip().rstrip("/"))
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        raise ValueError(f"invalid origin: {value}")
    if parsed.username is not None or parsed.password is not None or parsed.path or parsed.query or parsed.fragment:
        raise ValueError(f"origin must not contain credentials, path, query, or fragment: {value}")
    hostname = parsed.hostname.lower().rstrip(".")
    if not SAFE_HOST.fullmatch(hostname):
        raise ValueError(f"invalid origin host: {hostname}")
    port = parsed.port
    default_port = 443 if parsed.scheme == "https" else 80
    authority = hostname if not port or port == default_port else f"{hostname}:{port}"
    return f"{parsed.scheme}://{authority}"


def render(origin: str, public_host: str, cert: str, key: str, public_port: int) -> str:
    parsed = urlsplit(origin)
    upstream_host = parsed.hostname or ""
    public_suffix = "" if public_port == 443 else f":{public_port}"
    public_origin = f"https://{public_host}{public_suffix}"
    lines = [
        f"# generated by uniproxy panel for {origin}",
        "server {",
        "    listen 80;",
        "    listen [::]:80;",
        f"    server_name {public_host};",
        f"    return 301 {public_origin}$request_uri;",
        "}",
        "",
        "server {",
        "    listen 443 ssl;",
        "    listen [::]:443 ssl;",
        f"    server_name {public_host};",
        f"    ssl_certificate {nginx_string(cert)};",
        f"    ssl_certificate_key {nginx_string(key)};",
        "    location / {",
        f"        proxy_pass {origin};",
        "        proxy_http_version 1.1;",
        f"        proxy_set_header Host {nginx_string(parsed.netloc)};",
        "        proxy_ssl_server_name on;",
        f"        proxy_ssl_name {nginx_string(upstream_host)};",
        "        proxy_set_header Upgrade $http_upgrade;",
        "        proxy_set_header Connection 'upgrade';",
    ]
    lines.extend(f"        proxy_set_header {name} \"\";" for name in REQUEST_HEADERS_TO_DROP)
    lines.extend([
        f"        proxy_set_header Origin {nginx_string(origin)};",
        f"        proxy_set_header Referer {nginx_string(origin + '/')};",
        f"        proxy_redirect {origin} {public_origin};",
    ])
    lines.extend(f"        proxy_hide_header {name};" for name in RESPONSE_HEADERS_TO_DROP)
    lines.extend([
        "        proxy_buffering off;",
        "        proxy_read_timeout 300s;",
        "        proxy_send_timeout 300s;",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--suffix", required=True)
    parser.add_argument("--cert", required=True)
    parser.add_argument("--key", required=True)
    parser.add_argument("--public-port", required=True, type=int)
    args = parser.parse_args()
    if not 1 <= args.public_port <= 65535 or not SAFE_HOST.fullmatch(args.suffix):
        raise SystemExit("invalid public port or domain suffix")
    args.output.mkdir(parents=True, exist_ok=True)
    converted = 0
    for source in sorted(args.source.glob("*.caddy")):
        match = MARKER.search(source.read_text(encoding="utf-8"))
        if not match:
            continue
        public_host = source.stem.lower()
        if not SAFE_HOST.fullmatch(public_host) or not public_host.endswith("." + args.suffix):
            raise SystemExit(f"refusing unexpected generated host: {public_host}")
        origin = normalize_origin(match.group(1))
        target = args.output / f"{public_host}.conf"
        temporary = target.with_suffix(target.suffix + ".new")
        temporary.write_text(render(origin, public_host, args.cert, args.key, args.public_port), encoding="utf-8")
        os.replace(temporary, target)
        converted += 1
    print(f"converted={converted}")


if __name__ == "__main__":
    main()
