limit_req_zone $binary_remote_addr zone=uniproxy_admin:10m rate=30r/m;
limit_req_zone $binary_remote_addr zone=uniproxy_auth:10m rate=12r/m;
limit_req_zone $binary_remote_addr zone=uniproxy_user_actions:10m rate=30r/m;
limit_conn_zone $binary_remote_addr zone=uniproxy_ui_connections:10m;
